[options]
HoldPkg     = pacman glibc
Architecture = auto

Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 5

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# Lumen Repository (Placeholder)
#[lumen]
#SigLevel = Optional TrustAll
#Server = https://github.com/lumen-os/repo/raw/main/x86_64
