### Pamac configuration file

## When removing a package, also remove those dependencies that are
## not required by other installed packages (overwritten by LANG, see below):
RemoveUnusedDeps

## How many versions of cached packages to keep:
KeepNumPackages = 3

## Only check for updates:
#OnlyCheckUpdates

## Check AUR updates:
EnableAUR

## Check for updates every (in hours):
RefreshPeriod = 6

## No confirmation for installation:
#NoConfirmation

## Max parallel downloads:
MaxParallelDownloads = 4

## Check Flatpak updates:
EnableFlatpak
